### ISSUE TITLE
I ended up here from a link in “Jump Start Vue.js, 2nd Edition”

### ISSUE THREAD

**Issue by PerryCodes** [spbooks/csspro3#1]
Am I in the right place?

**Comment by simonmackie** [comment]
No, the link should go to [https://github.com/spbooks/jsvuejs2](https://github.com/spbooks/jsvuejs2). I'm sorry about that! Thanks for pointing out the error, @PerryCodes. I'll get that fixed.

**Comment by PerryCodes** [comment]
Apologies - I should have pointed out that the bad link was found here:
https://learning.oreilly.com/library/view/jump-start-vue-js/9781098129507/Text/jsvuejs2-preface.html#supp-mat

I've contacted O'Reilly regarding this error.

This link here is correct:
https://www.sitepoint.com/premium/books/jump-start-vue-js-2nd-edition/read/0/kt3lyhl9

**Comment by simonmackie** [comment]
Thanks @PerryCodes, I had already tracked it down. I've provided O'Reilly with an updated file so it should get fixed soon. Thanks once again for letting us know.
